version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gofiber:
    depends_on:
      - mongodb
    image: smootysmart/gofiber-app:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  mongo_data:
