name: deploy-GOFiber.yml

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list docker running containers
        run: docker ps -a

      - name: Pull latest Nginx image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gofiber-app:${{ github.sha }}

      - name: Deploy Nginx with Docker Compose
        run: docker compose -f docker-compose.yml up -d